version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=test
    networks:
      - common_network
    volumes:
      - postgres-data:/var/lib/postgresql/data
  order-service:
    build: ./orderservice
    ports:
      - "8081:8081"
    depends_on:
      - discovery-server
      - postgres
      - config-service
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=prod
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:8888
    networks:
      - common_network
  config-service:
    build: ./configserver
    ports:
      - "8888:8888"
    networks:
      - common_network
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/halitkalayci/microservices-configurations.git
      - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT-LABEL=master
  inventory-service:
    build: ./inventory.service
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
      - config-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8181/eureka
      - SPRING_CLOUD_CONFIG_PROFILE=dev
      - SPRING_CLOUD_CONFIG_IMPORT=configserver:http://config-service:8888
    networks:
      - common_network
  discovery-server:
    build: ./discoveryserver
    ports:
      - "8181:8181"
    networks:
      - common_network
  api_gateway:
    build: ./api-gateway
    ports:
      - "8010:8010"
    depends_on:
      - discovery-server
    networks:
      - common_network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8181/eureka


networks:
  common_network:

volumes:
  postgres-data:
    name: postgres-data
