version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=test
    networks:
      - common_network
    volumes:
      - postgres-data:/var/lib/postgresql/data
  order-service:
    build: ./orderservice
    ports:
      - "8081:8081"
    depends_on:
      - discovery-server
      - postgres
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8181/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/Northwind
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=test
    networks:
      - common_network
  inventory-service:
    build: ./inventory.service
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8181/eureka
      - SPRING_APPLICATION_NAME=dockerDeneme
    networks:
      - common_network
  discovery-server:
    build: ./discoveryserver
    ports:
      - "8181:8181"
    networks:
      - common_network
  api_gateway:
    build: ./api-gateway
    ports:
      - "8010:8010"
    depends_on:
      - discovery-server
    networks:
      - common_network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8181/eureka


networks:
  common_network:

volumes:
  postgres-data:
    name: postgres-data
