version: "3.8"

services:
  order-service:
    image: halitkalayci/orderservice
    ports:
      - "8081:8081"
      - "8082:8081"
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8181/eureka
    networks:
      - common_network
  inventory-service:
    build: ./inventory.service
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8181/eureka
      - SPRING_APPLICATION_NAME=dockerDeneme
    networks:
      - common_network
  discovery-server:
    build: ./discoveryserver
    ports:
      - "8181:8181"
    networks:
      - common_network
  api_gateway:
    build: ./api-gateway
    ports:
      - "8010:8010"
    depends_on:
      - discovery-server
    networks:
      - common_network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8181/eureka


networks:
  common_network:
